#!/bin/bash

set -ux
juju-log "install script"

juju-log "adding MapR archive"
apt-add-repository "deb http://package.mapr.com/releases/v1.1.1/ubuntu/ mapr optional"
apt-get update

HOSTNAME=`hostname -f`
IP_ADDRESS=`hostname -f | xargs dig +short`
juju-log "Private IP: ${IP_ADDRESS}"

# fixing hosts entry added by cloudinit
sed -i "s/127.0.1.1\(.*${HOSTNAME}.*\)/${IP_ADDRESS}\1/" /etc/hosts

juju-log "installing packages"
export DEBIAN_FRONTEND=noninteractive

MAPR_MASTER_PACKAGES="mapr-cldb mapr-jobtracker mapr-nfs mapr-webserver"
MAPR_ZK_PACKAGES="mapr-zookeeper"
MAPR_NODE_PACKAGES="mapr-fileserver mapr-tasktracker"
apt-get -y install -qq $MAPR_MASTER_PACKAGES $MAPR_ZK_PACKAGES $MAPR_NODE_PACKAGES

# first node... "master?"
#apt-get -y install -qq $MAPR_MASTER_PACKAGES $MAPR_ZK_PACKAGES $MAPR_NODE_PACKAGES
# nodes 2-3... "zk?"
#apt-get -y install -qq $MAPR_ZK_PACKAGES $MAPR_NODE_PACKAGES
# nodes 4+... "node?"
#apt-get -y install -qq $MAPR_NODE_PACKAGES

#should totally be separate services
# cldb / master
# zk
# zk
# zk
# node
# node
# node

# or.... just have master and slave
# and automatically detect zk when adding slaves...?
# i.e., every slave install zk, but only starts if master tells it to

mapr_already_configured() {
  false
}
configure_mapr() {
  MAPR_SERVER=/opt/mapr/server

  #/opt/mapr/server/configure.sh -C <node 1> -Z <node 1>,<node 2>,<node 3>
  $MAPR_SERVER/configure.sh -C <node 1> -Z <node 1>,<node 2>,<node 3>

  # move to configure.yaml
  #/opt/mapr/server/disksetup -F /tmp/disks.txt
  $MAPR_SERVER/disksetup -F /tmp/disks.txt

  # set bind-address...
  #sed -i 's###' /etc/hadoop/conf/hadoop-env.sh
  # -or-
  #echo "export HADOOP_OPTS=-Djava.net.preferIPv4Stack=true" >> /etc/hadoop/conf/hadoop-env.sh

}
mapr_already_configured || configure_mapr

if [ -x /usr/bin/open-port ];then
   open-port 50010/TCP
fi

